version: '3'

services:

    subscriber:
        build: ./subscriber
        container_name: subscriber
        entrypoint: dockerize -wait tcp://rabbit:5672 -timeout 30s bash -c "/subscriber"
        tty: true
        networks:
            - app-network
        depends_on:
            - rabbit

    publisher:
        build: ./publisher
        container_name: publisher
        entrypoint: dockerize -wait tcp://subscriber:8080 -timeout 30s bash -c "/publisher"
        tty: true
        networks:
            - app-network
        depends_on:
            - rabbit

    rabbit:
        image: "rabbitmq:3-management"
        networks:
            - app-network
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"

networks: 
    app-network:
        driver: bridge 